ingress:
  enabled: false
  ingressClassName: nginx
  annotations: 
    external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
    external-dns.alpha.kubernetes.io/target: "homelab-tunnel.sillock.co.uk"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: dotbot-api.sillock.co.uk
      paths: 
       - "/"
   tls: 
    - secretName: dotbot-tls-certificate
      hosts:
        - dotbot-api.sillock.co.uk
imageTag: v0.1.0